### ISSUE TITLE
accessing large files such as regBase_V1.1.gz from Drive

### ISSUE THREAD

**Issue by fl16180** [mulinlab/regBase#1]
Hello, I have tried a few different ways to download the largest regBase files from your Google Drive to a server, including curl and rclone. The other files have no issue but the largest ones, such as regBase_V1.1.gz give errors from Google such as:

```
2020/01/10 15:13:57 ERROR : regBase_V1.1.gz: Failed to copy: multpart copy: failed to open source: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
```

I am just wondering if anyone else has run into the issue or if you know a solution. Thank you!

**Comment by jrm3215** [comment]
@fl16180 I'm having a similar issue. Did you find a solution?

**Comment by fl16180** [comment]
@jrm3215 There's a download quota unless the file is in your own Google Drive. Add the file to your drive, then make a copy of it in the drive, then download the copy. (If you just add without making a copy, Google Drive only stores a link to the original)

**Comment by jrm3215** [comment]
Thanks @fl16180 ! Looks like the file is syncing now.

**Comment by frequena** [comment]
Thanks @fl16180 , it worked! It would be nice if the authors provide an alternative way to get access to the data
